### ISSUE TITLE
Test error when creating user

### ISSUE THREAD

**Issue by patrickpr** [heiglandreas/authLdap#39] opened 2015-03-19 22:53 UTC
Hi,

Got an error when logging in with a new LDAP user. The problem was the admin I manually created with WP had the same mail address than my ldap user. 
The worst thing is that it does not report it even in debug mode and server gives a 500 error : 

 PHP Catchable fatal error:  Object of class WP_Error could not be converted to string in /var/www/[.....]/wp-content/plugins/authldap/authLdap.php on line 345

Made this quick fix at least to have the info in debug mode, but a clear message back to the user should be great if possible.

-------------------- (starting line  342 of authLdap.php)
       // if the user exists, wp_insert_user will update the existing user record
        $userid = wp_insert_user($user_info);

        // CODE ADDED
        if( !is_wp_error($userid) ) {
           authLdap_debug('user id = ' . $userid);
        } else {
           authLdap_debug('Error creating user : ' . $userid->get_error_message());     
           throw new UnexpectedValueException('Error creating user'); 
        }       
         // END CODE ADDED
        // flag the user as an ldap user so we can hide the password fields in the user profile 
        update_user_meta($userid, 'authLDAP', true);
------------------------------

And thanks for the plugin.

Regards,

Patrick

**Comment by heiglandreas** [comment] 2015-03-19 23:40
This is a duplicate of #20. Thanks for the fix which I will implement tomorrow.

**Comment by heiglandreas** [comment] 2015-03-29 21:10
@patrickpr We can't actually give a hint on the login-page but I added a log-entry to the authLDAP-debug log as well as to the error-log of the web-server. 

As a failing LDAP-login falls back to authenticating against the default wordpress-database only their error-messages are displayed in the login form :frowning:

**Closed by heiglandreas** 2015-03-29 21:10 UTC
