### ISSUE TITLE
Query not able to return groups for user

### ISSUE THREAD

**Issue by pbbunny** [heiglandreas/authLdap#38] opened 2015-03-19 14:56 UTC
Somehow, certain users with the same search filters and ldap URI and settings, are showing as not members of any group when performing the ldap query.  The same search string is performed on the server, as well as from a different source, with results. The error log is not showing any error, just a result value of [] for groups for the user.  The group filter is using DN instead of UID.

**Comment by heiglandreas** [comment] 2015-03-19 15:35
Any funny characters in the search string? can you give me a sample of which users work an dwhich don't? Hard to debug otherwise :wink:

**Comment by heiglandreas** [comment] 2015-03-29 21:17
Hey @pbbunny  - Any news on this one?

**Comment by kidburglar** [comment] 2015-04-25 19:45
I think I have something same.

I have a user in a role group but the wordpress logs says that it is not true.
https://zerobin.net/?3e58d6d494468772#qtPiZBxiZF1PXDLA4KGV3AhI4fN3xYJPtCH5opDEdjg=

I set "cn" for group-attribute
Here a dump of my role
https://zerobin.net/?5d18cfc1de485ce4#cZCkljhu4/5u8K13iMEgRgf/pMJJLNVZxsCzgdlO4+M=

**Comment by heiglandreas** [comment] 2015-04-26 07:17
@kidburglar Have you verified that the DN of the user in question actually is the same as the one given in the ```roleOccupant```-attribute? I've just recently had the case where the DN of the user had been changed in our LDAP and the associated DN in a ```uniqueMember```-Attribute hasn't been changed accordingly.

**Comment by kidburglar** [comment] 2015-04-26 11:14
@heiglandreas : 
I just verify and it is the same.
Do you will the configuration in wordpress (if it can help) ?
Or create another bug, if you think that the issue is not the same.

**Comment by heiglandreas** [comment] 2015-04-26 12:35
OK. Then I'd be great when you could proviude me with the configuration as well as with an example result of a user-query and a group-query of your LDAP. I.e ```ldapsearch uid=exampleuser``` and ```ldapsearch cn=examplegroup``` (group is already available in your zerobin). I'll then see what I can do.

**Comment by kidburglar** [comment] 2015-04-26 13:03
@heiglandreas 
I feel bad...
My wordpress install must have something wrong.

I reinstall all yesterday (after test the plugin).
And now all work fine...

Thanks for all help and sorry for disturb.

**Comment by heiglandreas** [comment] 2015-04-26 13:07
Hey! Excellent news! :+1: 

No need to be sorry! :smile:  ANd thanks for reporting so fast!

**Comment by heiglandreas** [comment] 2015-04-26 13:09
Hey @pbbunny. As you didn't respond I'll assume that the issue is solved for you and close it. If that's incorrect **please** reopen the issue!

**Closed by heiglandreas** 2015-04-26 13:09 UTC
Labels: configuration, question
