### ISSUE TITLE
 [AuthLDAP] LDAP authentication failed

### ISSUE THREAD

**Issue by gausan** [heiglandreas/authLdap#136] opened 2017-08-08 14:31 UTC
Hello,

I use [AuthLDAP] for my wordpress authentification with LDAP (using bind user and password).
I have the error [AuthLDAP] LDAP authentication failed with exception: does not provide a scheme

Please can you send an example of LDAP URI to use with bind user and password for the plugin ?

Thanks in advance.

**Comment by heiglandreas** [comment] 2017-08-08 14:41
You should prefix the LDAP-URI with ```ldap://``` or ```ldap://``` so that it for example reads like this:

    ldap://user:passowrd@ldap.example.com:396/dc=example,dc=com

Does that help you?

**Comment by heiglandreas** [comment] 2017-08-08 14:44
You should URL-Encode the password when there are special characters in it. Especially when it contains '@' or ':' ;)

**Comment by gausan** [comment] 2017-08-08 14:57
Yes I tried it already and my error is 
Notice: No bind successfull. Exception thrown in line 68 in /var/www/wordpress/wp-content/plugins/authldap/authLdap.php on line 410

As our LDAP does not accept anonymous connection I send the bindname and x-bindpw too and having this error.

**Comment by heiglandreas** [comment] 2017-08-08 15:01
What's the bind-name you are using and are there any special characters in the password? Are those URL-Encoded? Can you reproduce the failure on the command line of the server in question (to eliminate network issues) or does f.e. an ```ldapsearch``` work?

**Comment by heiglandreas** [comment] 2017-08-08 15:01
Do you use ```ldaps``` with a self-signed certificate?

**Comment by gausan** [comment] 2017-08-08 15:08
Ldapsearch works well on the server and there are no special characters on password.

There are no certificates but ldap is connected with an authorized account used in the URL for bind.

**Comment by heiglandreas** [comment] 2017-08-08 15:19
what BindDN do you use with ldapsearch? is it an email-address or a DN? when it's an email-address, did you urlencode the '@'?

**Comment by gausan** [comment] 2017-08-09 06:55
No I'm using a DN

ldap://ldap.com:389/o=xxxx?uid?sub?(objectClass=person)?!bindname=uid=username,x-bindpw=secret

**Comment by heiglandreas** [comment] 2017-08-09 07:56
Ah OK! That's a great concept of configuring an LDAP-Connection! Sadly it doesn't work with authLdap ☹️ 

The LDAP-URI you are looking for in this case is this:

    ldap://uid=username:secret@ldap.com:389/o=xxxx

Remember to URL-Encode ```username``` and ```secret```.

That should do the trick.

**Comment by gausan** [comment] 2017-08-09 07:57
I tried different combinations but getting error 
PHP Notice:  No bind successfull. Exception thrown in line 68 in /var/www/wordpress/wp-content/plugins/authldap/authLdap.php on line 410

**Comment by gausan** [comment] 2017-08-09 08:02
With the new one you provided I'm getting error 
 [AuthLDAP] LDAP authentication failed with exception: bind was not successfull: Can't contact LDAP server

**Comment by heiglandreas** [comment] 2017-08-09 08:14
That indicates that there seems to be a problem connecting to the LDAP-Server on the given port. 

That can have different reasons: 

* When you use plain LDAP on Port 389 make sure that the server that is running the WordPress-installation can actually connect to the server on the given port. You can test that f.e. on linux with ```telnet server port```. When that results in a ```Connected to server``` the connection itself should work. Then the LDAP-Server might not accept connections. You can test that by using ```ldapsearch -h server uid=*```. When that results in an error message that the server could not be reached, that issue should be fixed. If the ```ldapsearch``` can get through to the server , the connection should work.

* When you use ```ldap``` or ```ldap+tls``` the whole certificate-juggling issue can cause the connection to fail. Then you'll need to fix that depending on the certificate-details…

Without knowing more details I sadly can'T help you there…

**Comment by gausan** [comment] 2017-08-09 09:33
telnet and ldapsearch is OK
We are using LDAP without TLS.

**Comment by heiglandreas** [comment] 2017-08-09 10:40
telnet and ldapsearch from the server running WordPress. And you are running plain LDAP.

Did you try the IP-Address of the LDAP instead of the FQDN?

**Comment by heiglandreas** [comment] 2017-08-09 10:42
Perhaps we should move this discussion to [Gitter](https://gitter.im/heiglandreas/authLdap)

**Comment by heiglandreas** [comment] 2017-08-13 17:45
Any news on this one?

**Comment by heiglandreas** [comment] 2018-01-19 07:41
Seems to be resolved…

**Closed by heiglandreas** 2018-01-19 07:41 UTC
